name: sejourne_pms
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

#--------------- Packages ------------#
dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  localization:

  # Utility Packages
  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.4
  flutter_zoom_drawer: ^3.2.0
  smooth_page_indicator: ^1.1.0
  emoji_extension: ^1.1.1
  dropdown_button2: ^2.3.9
  flutter_svg: ^2.0.10+1
  dotted_border: ^2.1.0
  pinput: ^4.0.0
  share_plus: ^9.0.0
  buttons_tabbar: ^1.3.8
  fl_country_code_picker: ^0.1.9+1
  intl_phone_field: ^3.2.0
  country_pickers: ^3.0.1
  app_settings: ^5.1.1
  device_preview: ^1.2.0
  group_button: ^5.3.4
  flutter_emoji_feedback: ^0.3.0
  flutter_app_info: ^1.1.2
  animated_custom_dropdown: ^3.1.1
  easy_date_timeline: ^1.1.3
  flutter_easy_faq: ^1.0.1
  animate_do: ^3.3.4


  # Images
  lottie: ^2.6.0
  shimmer: ^3.0.0
  gallery_zoom_slides: ^0.1.3
  fullscreen_image_viewer: ^0.0.6
  image_picker: ^1.1.0
  photo_view: ^0.15.0
  flexi_productimage_slider: ^1.1.1


  #icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.1

  # Network
  dio: ^5.4.3+1
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.2
  webview_flutter: ^4.7.0
  webview_flutter_android: any
  webview_flutter_wkwebview: any

  #Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  shadow_overlay: ^1.0.5

  # Firebase and Google Maps
  firebase_core: ^2.24.2
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1
  google_sign_in: ^6.2.1
  google_maps_flutter: ^2.5.2
  google_maps_cluster_manager_2: ^3.1.0
  syncfusion_flutter_datepicker: ^26.1.38
  geolocator: ^12.0.0
  intl_phone_number_input: ^0.7.4
  country_code_picker: ^3.0.0
  fl_chart: ^0.68.0









  #---------------- ./Packages END -------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/sejourneLogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"


flutter:
  uses-material-design: true

  #---------------- LOCAL ASSETS -------------#
  assets:
    - assets/logos/
    - assets/icons/
    - assets/icons/bottom_nav_bar_icons/
    - assets/icons/profile_icons/
    - assets/icons/bookings_icons/
    - assets/icons/map/
    - assets/images/background_images/
    - assets/images/animation/
    - assets/images/banners/
    - assets/icons/calender/
    - assets/images/onBoarding/
    - assets/icons/permissions_icons/
    - assets/icons/chat_screen_icons/
    - assets/icons/search_screen_icons/
    - assets/images/home_location_list/
    - assets/images/properties/
    - assets/images/profile/
    - assets/icons/messages_icons/
    - assets/icons/product_details_icons/
    - assets/icons/profile_icons/personal_information/
    - assets/icons/profile_icons/preferences/
    - assets/icons/profile_icons/security/
    - assets/icons/profile_icons/legal_information/
    - assets/icons/profile_icons/support/
    - assets/icons/profile_icons/settings/
    - assets/icons/profile_icons/document/
    - assets/icons/profile_icons/reviews/
    - assets/icons/profile_icons/reports/
    - assets/icons/bookings_icons/write_review_icons/
    - assets/icons/drawer_icons/
    - assets/images/drawer/
    - assets/icons/home_icons/
    - assets/languages/
    - assets/map_style/

  #---------------- LOCAL FONTS -------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800






